# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 676)
        MainWindow.setMinimumSize(QtCore.QSize(0, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Consulta = QtWidgets.QFrame(self.centralwidget)
        self.Consulta.setGeometry(QtCore.QRect(280, 10, 421, 211))
        self.Consulta.setStyleSheet("background-color: #AAA;  color:blue")
        self.Consulta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Consulta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Consulta.setObjectName("Consulta")
        self.pushButton = QtWidgets.QPushButton(self.Consulta)
        self.pushButton.setGeometry(QtCore.QRect(280, 70, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.Consulta)
        self.textEdit.setGeometry(QtCore.QRect(140, 70, 104, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.Consulta)
        self.label_2.setGeometry(QtCore.QRect(60, 140, 67, 17))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.Consulta)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 140, 141, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.Consulta)
        self.label.setGeometry(QtCore.QRect(60, 80, 67, 17))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.Consulta)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 140, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.Consulta)
        self.label_3.setGeometry(QtCore.QRect(180, 20, 67, 17))
        self.label_3.setObjectName("label_3")
        self.CRUD = QtWidgets.QFrame(self.centralwidget)
        self.CRUD.setGeometry(QtCore.QRect(10, 240, 431, 391))
        self.CRUD.setStyleSheet("background-color: #AAA;  color:blue")
        self.CRUD.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CRUD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CRUD.setObjectName("CRUD")
        self.pushButton_3 = QtWidgets.QPushButton(self.CRUD)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 120, 91, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.CRUD)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 70, 104, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(self.CRUD)
        self.label_6.setGeometry(QtCore.QRect(160, 10, 111, 17))
        self.label_6.setObjectName("label_6")
        self.textEdit_5 = QtWidgets.QTextEdit(self.CRUD)
        self.textEdit_5.setGeometry(QtCore.QRect(160, 70, 101, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.CRUD)
        self.textEdit_6.setGeometry(QtCore.QRect(310, 70, 104, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.CRUD)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 180, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_7 = QtWidgets.QTextEdit(self.CRUD)
        self.textEdit_7.setGeometry(QtCore.QRect(120, 180, 81, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_4 = QtWidgets.QTextEdit(self.CRUD)
        self.textEdit_4.setGeometry(QtCore.QRect(120, 240, 104, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_8 = QtWidgets.QTextEdit(self.CRUD)
        self.textEdit_8.setGeometry(QtCore.QRect(240, 240, 101, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.CRUD)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 290, 91, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit_9 = QtWidgets.QTextEdit(self.CRUD)
        self.textEdit_9.setGeometry(QtCore.QRect(350, 240, 71, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.CRUD)
        self.textEdit_10.setGeometry(QtCore.QRect(20, 240, 81, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.CRUD_2 = QtWidgets.QFrame(self.centralwidget)
        self.CRUD_2.setGeometry(QtCore.QRect(490, 240, 431, 391))
        self.CRUD_2.setStyleSheet("background-color: #AAA;  color:blue")
        self.CRUD_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CRUD_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CRUD_2.setObjectName("CRUD_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.CRUD_2)
        self.pushButton_6.setGeometry(QtCore.QRect(230, 60, 91, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit_11 = QtWidgets.QTextEdit(self.CRUD_2)
        self.textEdit_11.setGeometry(QtCore.QRect(80, 60, 104, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.label_7 = QtWidgets.QLabel(self.CRUD_2)
        self.label_7.setGeometry(QtCore.QRect(160, 10, 111, 17))
        self.label_7.setObjectName("label_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.CRUD_2)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 130, 89, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.textEdit_15 = QtWidgets.QTextEdit(self.CRUD_2)
        self.textEdit_15.setGeometry(QtCore.QRect(230, 210, 104, 31))
        self.textEdit_15.setObjectName("textEdit_15")
        self.pushButton_8 = QtWidgets.QPushButton(self.CRUD_2)
        self.pushButton_8.setGeometry(QtCore.QRect(170, 280, 91, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit_18 = QtWidgets.QTextEdit(self.CRUD_2)
        self.textEdit_18.setGeometry(QtCore.QRect(80, 210, 101, 31))
        self.textEdit_18.setObjectName("textEdit_18")
        self.textEdit_12 = QtWidgets.QTextEdit(self.CRUD_2)
        self.textEdit_12.setGeometry(QtCore.QRect(80, 130, 104, 31))
        self.textEdit_12.setObjectName("textEdit_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Consultar"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Id del Doctor"))
        self.label_2.setText(_translate("MainWindow", "Hospital"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "Nombre Hospital"))
        self.label.setText(_translate("MainWindow", "Doctor"))
        self.pushButton_2.setText(_translate("MainWindow", "Consultar"))
        self.label_3.setText(_translate("MainWindow", "Consulta"))
        self.pushButton_3.setText(_translate("MainWindow", "Agregar"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.label_6.setText(_translate("MainWindow", "CRUD Doctor"))
        self.textEdit_5.setPlaceholderText(_translate("MainWindow", "Especialidad"))
        self.textEdit_6.setPlaceholderText(_translate("MainWindow", "Hospital"))
        self.pushButton_5.setText(_translate("MainWindow", "Eliminar"))
        self.textEdit_7.setPlaceholderText(_translate("MainWindow", "Id. Doctor"))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.textEdit_8.setPlaceholderText(_translate("MainWindow", "Especialidad"))
        self.pushButton_4.setText(_translate("MainWindow", "Actualizr"))
        self.textEdit_9.setPlaceholderText(_translate("MainWindow", "Hospital"))
        self.textEdit_10.setPlaceholderText(_translate("MainWindow", "Id. Doctor"))
        self.pushButton_6.setText(_translate("MainWindow", "Agregar"))
        self.textEdit_11.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.label_7.setText(_translate("MainWindow", "CRUD Hospital"))
        self.pushButton_7.setText(_translate("MainWindow", "Eliminar"))
        self.textEdit_15.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.pushButton_8.setText(_translate("MainWindow", "Actualizr"))
        self.textEdit_18.setPlaceholderText(_translate("MainWindow", "Id. Hospital"))
        self.textEdit_12.setPlaceholderText(_translate("MainWindow", "Id.Hospital"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
